server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SamanviRaj/config-server.git
          clone-on-start: true
          #username: your_git_username
          #password: your_git_password
          #search-paths: config-repo
          default-label: master

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

